<#
.SYNOPSIS
    Puts myIDE on the Desktop and in the Start menu.

.DESCRIPTION
    The Start-menu entry is the one that matters: Windows Start search reads the
    Programs folder from its app-list cache, not from the file index, so a
    Desktop-only shortcut never turns up when you tap Win and type "myIDE".

    The shortcut runs myide.vbs, which starts Electron with no console window.
    Pointing it straight at powershell.exe works too, but flashes a black box on
    every launch.

.EXAMPLE
    .\install.ps1
    .\install.ps1 -Remove
#>
[CmdletBinding()]
param(
    [switch]$Remove
)

$ErrorActionPreference = 'Stop'
$Root = $PSScriptRoot
$LinkName = 'myIDE.lnk'

$targets = @(
    [IO.Path]::Combine([Environment]::GetFolderPath('Desktop'), $LinkName),
    [IO.Path]::Combine([Environment]::GetFolderPath('Programs'), $LinkName)
)

if ($Remove) {
    foreach ($t in $targets) {
        if (Test-Path $t) { Remove-Item $t -Force; Write-Host "Removed $t" -ForegroundColor Yellow }
    }
    return
}

if (-not (Test-Path (Join-Path $Root 'node_modules\electron'))) {
    throw "Dependencies are missing. Run 'npm install' in $Root first."
}

# A .vbs launcher because WScript.Shell can start a process with no window at
# all; -WindowStyle Hidden on powershell.exe still flashes briefly.
$vbs = Join-Path $Root 'myide.vbs'
@"
' Starts myIDE with no console window. Generated by install.ps1.
Set shell = CreateObject("WScript.Shell")
shell.CurrentDirectory = "$Root"
shell.Run "cmd /c npm start", 0, False
"@ | Set-Content -Path $vbs -Encoding ASCII

# Electron ships an icon we can reuse rather than inventing one.
$icon = Join-Path $Root 'node_modules\electron\dist\electron.exe'

$shell = New-Object -ComObject WScript.Shell
foreach ($t in $targets) {
    $sc = $shell.CreateShortcut($t)
    $sc.TargetPath = "$env:SystemRoot\System32\wscript.exe"
    $sc.Arguments = "`"$vbs`""
    $sc.WorkingDirectory = $Root
    $sc.IconLocation = "$icon,0"
    $sc.Description = 'myIDE - Python for DSA practice'
    $sc.Save()
    Write-Host "Created $t" -ForegroundColor Green
}

Write-Host "`nTap Windows and type 'myIDE' to launch it." -ForegroundColor Cyan
